.

diff --git a/.config/hypr/scripts/auto-upgrade b/.config/hypr/scripts/auto-upgrade
--- a/.config/hypr/scripts/auto-upgrade
+++ b/.config/hypr/scripts/auto-upgrade
@@ -5,10 +5,10 @@ which checkupdates && echo "checkupdates dependency satisfied" || sudo pacman -S
 out_of_date_packs=$(checkupdates | wc -l)
 OUTDATED_ALLOWED=50
 
-# Only update if >= 30 packages are out of date (idea: stabe system intervalls)
+# Only update if >= X packages are out of date (idea: stabe system intervalls)
 if [[ $out_of_date_packs -ge $OUTDATED_ALLOWED ]]; then
-  kitty --name "Auto_Update" --title "Auto_Update" sh -c "echo 'Requesting System upgrade ($out_of_date_packs packages)';sudo pacman -Syu --noconfirm; read -n 1 -s -p 'Press [ANY]-key to continue ...' dummy;"
-  [ $? -ne 0 ] && echo "Auto Update Success" || (echo "Auto Update Failed" && sudo pacman -Syu)
+  kitty --hold --name "Auto_Update" --title "Auto_Update" sh -c "echo 'Requesting System upgrade ($out_of_date_packs packages)';sudo pacman -Syu --noconfirm; read -n 1 -s -p 'Press [ANY]-key to continue ...' dummy;"
+  [ $? -ne 0 ] && echo "Auto Update Success" || (echo "Auto Update Failed" && kitty --hold --name "Auto_Update" --title "Auto_Update" sh -c "sudo pacman -Syu")
 else
   echo "Less than $OUTDATED_ALLOWED packages outdated => skipping update"
 fi
